name: Deployments

on:
  push:
    tags:
      - zbus-*
    paths:
      - book/**/*
      - book-1.0/**/*
      - .github/workflows/deploy.yml

jobs:
  book:
    runs-on: ubuntu-large
    permissions:
      contents: write # To push a branch
      pull-requests: write # To create a PR from that branch
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install latest mdbook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Build Books
        run: |
          mdbook build book
          mdbook build book-1.0
          mkdir -p public/1.0
          cp -r ./book/book/* ./public
          cp -r ./book-1.0/book/* ./public/1.0/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
